services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - db-data:/app/instance
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
