"""add task position

Revision ID: 87436939ddff
Revises: aebb545b8a2d
Create Date: 2026-06-30 01:08:59.814889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87436939ddff'
down_revision = 'aebb545b8a2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_activity_log_team'))
        batch_op.drop_index(batch_op.f('ix_activity_team_created'))

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_comment_team'))

    with op.batch_alter_table('custom_field', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_custom_field_team'))

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_notification_team'))
        batch_op.drop_index(batch_op.f('ix_notification_team_user_unread'), sqlite_where=sa.text('read = 0'))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_project_team'))

    with op.batch_alter_table('project_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_template_team'))
        batch_op.drop_index(batch_op.f('ix_project_template_team_key'))

    with op.batch_alter_table('recurring_task', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_recurring_task_team'))

    with op.batch_alter_table('saved_filter', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_saved_filter_team'))

    with op.batch_alter_table('subtask', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_subtask_team'))

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_tag_team'))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=False))
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_task_team'))
        batch_op.drop_index(batch_op.f('ix_task_team_due'), sqlite_where=sa.text('completed = 0'))
        batch_op.drop_index(batch_op.f('ix_task_team_status'))

    with op.batch_alter_table('task_dependency', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_task_dependency_team'))

    with op.batch_alter_table('task_template', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_task_template_team'))

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_archived'))

    with op.batch_alter_table('team_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_action_time'))
        batch_op.drop_index(batch_op.f('ix_audit_actor'))

    with op.batch_alter_table('team_invite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_team'))
        batch_op.drop_index(batch_op.f('ix_invite_unconsumed'), sqlite_where=sa.text('consumed_at IS NULL'))

    # Backfill: set position for existing tasks based on created_at order per team
    conn = op.get_bind()
    for row in conn.execute(sa.text("SELECT DISTINCT team_id FROM task")).fetchall():
        tid = row[0]
        tasks = conn.execute(
            sa.text("SELECT id FROM task WHERE team_id = ? ORDER BY created_at ASC, id ASC"),
            (tid,),
        ).fetchall()
        for idx, (task_id,) in enumerate(tasks):
            conn.execute(
                sa.text("UPDATE task SET position = ? WHERE id = ?"),
                (idx, task_id),
            )

    # Also backfill any tasks with NULL team_id (super_admin tasks, if any)
    null_team_tasks = conn.execute(
        sa.text("SELECT id FROM task WHERE team_id IS NULL ORDER BY created_at ASC, id ASC")
    ).fetchall()
    for idx, (task_id,) in enumerate(null_team_tasks):
        conn.execute(
            sa.text("UPDATE task SET position = ? WHERE id = ?"),
            (idx, task_id),
        )

    # Create a composite index on (team_id, position) for efficient ordering
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_team_position'), ['team_id', 'position'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_invite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_unconsumed'), ['team_id'], unique=False, sqlite_where=sa.text('consumed_at IS NULL'))
        batch_op.create_index(batch_op.f('ix_invite_team'), ['team_id'], unique=False)

    with op.batch_alter_table('team_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_actor'), ['actor_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_action_time'), ['action', 'created_at'], unique=False)

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_archived'), ['archived'], unique=False)

    with op.batch_alter_table('task_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_template_team'), ['team_id'], unique=False)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('task_dependency', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_dependency_team'), ['team_id'], unique=False)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_team_status'), ['team_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_team_due'), ['team_id', 'due_date'], unique=False, sqlite_where=sa.text('completed = 0'))
        batch_op.create_index(batch_op.f('ix_task_team'), ['team_id'], unique=False)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('position')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_team'), ['team_id'], unique=False)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('subtask', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subtask_team'), ['team_id'], unique=False)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('saved_filter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_filter_team'), ['team_id'], unique=False)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('recurring_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_task_team'), ['team_id'], unique=False)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('project_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_template_team_key'), ['team_id', 'source_catalogue_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_template_team'), ['team_id'], unique=False)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_team'), ['team_id'], unique=False)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_team_user_unread'), ['team_id', 'user_id'], unique=False, sqlite_where=sa.text('read = 0'))
        batch_op.create_index(batch_op.f('ix_notification_team'), ['team_id'], unique=False)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('custom_field', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_field_team'), ['team_id'], unique=False)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_team'), ['team_id'], unique=False)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_team_created'), ['team_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_team'), ['team_id'], unique=False)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
