"""add team, team_invite, team_audit_log tables

Revision ID: a0a6a0fd5858
Revises: b8e4c6f2a901
Create Date: 2026-05-24 12:35:01.766549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a6a0fd5858'
down_revision = 'b8e4c6f2a901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), server_default='', nullable=False),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('team_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_team_id', sa.Integer(), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('source_team_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['source_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['target_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('consumed_by_id', sa.Integer(), nullable=True),
    sa.Column('default_role', sa.String(length=20), server_default='user', nullable=False),
    sa.ForeignKeyConstraint(['consumed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )

    # Indexes per design 3.1
    # Team: case-insensitive uniqueness scoped to non-archived rows.
    # Postgres supports functional partial unique index; on SQLite we fall back
    # to a plain unique on lower(name) which is enough for our small dataset.
    op.create_index(
        'ix_team_name_lower',
        'team',
        [sa.text('LOWER(name)')],
        unique=True,
        postgresql_where=sa.text('archived = false'),
        sqlite_where=sa.text('archived = 0'),
    )
    op.create_index('ix_team_archived', 'team', ['archived'])

    # TeamInvite: lookup by team, plus partial index of unconsumed invites for fast
    # 'active invites for team' queries.
    op.create_index('ix_invite_team', 'team_invite', ['team_id'])
    op.create_index(
        'ix_invite_unconsumed',
        'team_invite',
        ['team_id'],
        postgresql_where=sa.text('consumed_at IS NULL'),
        sqlite_where=sa.text('consumed_at IS NULL'),
    )

    # TeamAuditLog: super-admin queries are usually 'recent actions by actor'
    # or 'recent actions of action type', both ordered by created_at DESC.
    op.create_index('ix_audit_actor', 'team_audit_log', ['actor_id', sa.text('created_at DESC')])
    op.create_index('ix_audit_action_time', 'team_audit_log', ['action', sa.text('created_at DESC')])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_action_time', table_name='team_audit_log')
    op.drop_index('ix_audit_actor', table_name='team_audit_log')
    op.drop_index('ix_invite_unconsumed', table_name='team_invite')
    op.drop_index('ix_invite_team', table_name='team_invite')
    op.drop_index('ix_team_archived', table_name='team')
    op.drop_index('ix_team_name_lower', table_name='team')
    op.drop_table('team_invite')
    op.drop_table('team_audit_log')
    op.drop_table('team')
    # ### end Alembic commands ###
