"""add password_reset_token table

Revision ID: db04425f80ae
Revises: 2c8e44f754b0
Create Date: 2026-06-08 02:02:11.239560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db04425f80ae'
down_revision = '2c8e44f754b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_activity_log_team'))
        batch_op.drop_index(batch_op.f('ix_activity_team_created'))

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_comment_team'))

    with op.batch_alter_table('custom_field', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_custom_field_team'))

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_notification_team'))
        batch_op.drop_index(batch_op.f('ix_notification_team_user_unread'), sqlite_where=sa.text('read = 0'))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_project_team'))

    with op.batch_alter_table('project_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_template_team'))
        batch_op.drop_index(batch_op.f('ix_project_template_team_key'))

    with op.batch_alter_table('recurring_task', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_recurring_task_team'))

    with op.batch_alter_table('saved_filter', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_saved_filter_team'))

    with op.batch_alter_table('subtask', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_subtask_team'))

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_tag_team'))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_task_team'))
        batch_op.drop_index(batch_op.f('ix_task_team_due'), sqlite_where=sa.text('completed = 0'))
        batch_op.drop_index(batch_op.f('ix_task_team_status'))

    with op.batch_alter_table('task_dependency', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_task_dependency_team'))

    with op.batch_alter_table('task_template', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_task_template_team'))

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_archived'))

    with op.batch_alter_table('team_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_action_time'))
        batch_op.drop_index(batch_op.f('ix_audit_actor'))

    with op.batch_alter_table('team_invite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_team'))
        batch_op.drop_index(batch_op.f('ix_invite_unconsumed'), sqlite_where=sa.text('consumed_at IS NULL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_invite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_unconsumed'), ['team_id'], unique=False, sqlite_where=sa.text('consumed_at IS NULL'))
        batch_op.create_index(batch_op.f('ix_invite_team'), ['team_id'], unique=False)

    with op.batch_alter_table('team_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_actor'), ['actor_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_action_time'), ['action', 'created_at'], unique=False)

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_archived'), ['archived'], unique=False)

    with op.batch_alter_table('task_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_template_team'), ['team_id'], unique=False)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('task_dependency', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_dependency_team'), ['team_id'], unique=False)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_team_status'), ['team_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_team_due'), ['team_id', 'due_date'], unique=False, sqlite_where=sa.text('completed = 0'))
        batch_op.create_index(batch_op.f('ix_task_team'), ['team_id'], unique=False)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_team'), ['team_id'], unique=False)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('subtask', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subtask_team'), ['team_id'], unique=False)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('saved_filter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_filter_team'), ['team_id'], unique=False)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('recurring_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_task_team'), ['team_id'], unique=False)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('project_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_template_team_key'), ['team_id', 'source_catalogue_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_template_team'), ['team_id'], unique=False)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_team'), ['team_id'], unique=False)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_team_user_unread'), ['team_id', 'user_id'], unique=False, sqlite_where=sa.text('read = 0'))
        batch_op.create_index(batch_op.f('ix_notification_team'), ['team_id'], unique=False)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('custom_field', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_field_team'), ['team_id'], unique=False)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_team'), ['team_id'], unique=False)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_team_created'), ['team_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_team'), ['team_id'], unique=False)
        batch_op.alter_column('team_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('password_reset_token')
    # ### end Alembic commands ###
